default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: company_dw
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: company_dw
      schema: public
      threads: 4
      keepalives_idle: 0