version: "3.8"

services:
  company_db:
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: company_db
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "company_db"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
      volumes:
        - ./postgres_database/init.sql:/docker-entrypoint-initdb.d/init.sql
  airflowdb:
    image: postgres
    environment:
      POSTGRES_DB: 'airflow'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      company_db:
        condition: service_healthy
  dw:
    image: postgres
    environment:
      POSTGRES_DB: 'company_dw'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 54321:5432
  external_data:
    build:
      context: .
      dockerfile: ./external_data/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        WEATHER_API_KEY: $WEATHER_API_KEY
    depends_on:
      dw:
        condition: service_healthy
  airflow:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    restart: always
    environment:
        LOAD_EX: n
        EXECUTOR: Local
        AIRFLOW__CORE__FERNET_KEY: GmhP3ADRHscUZ2z_ohwMOmXlu5jFSI5IQRG0s-KrV_Y=
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflowdb:5432/airflow
        AIRFLOW_CONN_COMPANY_DW: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dw:5432/company_dw"
        AIRFLOW_CONN_COMPANY_DB: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@company_db:5432/company_db
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ./airflow/dags:/usr/local/airflow/dags
        - ./dbt/dbt_company:/usr/local/airflow/dbt
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
    depends_on:
      generator:
        condition: service_completed_successfully
  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
    ports:
        - "8088:8088"
    command:     gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    depends_on:
      - airflow
