slice_name: Possible Future Revenue
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 1__table
  viz_type: table
  slice_id: 14
  query_mode: aggregate
  groupby:
  - regional_office
  - ts_engage_date
  - product_name
  - deal_age
  time_grain_sqla: P1M
  temporal_columns_lookup:
    ts_engage_date: true
    ts_close_date: true
    date_actual: true
    first_day_of_week: true
    last_day_of_week: true
    last_day_of_quarter: true
    first_day_of_year: true
    first_day_of_month: true
    last_day_of_month: true
    first_day_of_quarter: true
    last_day_of_year: true
  metrics:
  - suggested_retail_price
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_vlglp171laq_a02ymkf2hu8
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: ts_close_date is null
    subject: ts_close_date
  timeseries_limit_metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: regional_office, product_name
    optionName: metric_7kn5lq10gwe_kwq0h6oedu
    sqlExpression: regional_office, product_name
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: false
  show_totals: true
  table_timestamp_format: smart_date
  show_cell_bars: false
  color_pn: true
  conditional_formatting:
  - colorScheme: '#ACE1C4'
    column: suggested_retail_price
    operator: None
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1M","having":"","where":"(ts_close_date
  is null)"},"applied_time_extras":{},"columns":["regional_office",{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"ts_engage_date","label":"ts_engage_date","expressionType":"SQL"},"product_name","deal_age"],"metrics":["suggested_retail_price"],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"regional_office,
  product_name","optionName":"metric_7kn5lq10gwe_kwq0h6oedu","sqlExpression":"regional_office,
  product_name"},true]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"regional_office,
  product_name","optionName":"metric_7kn5lq10gwe_kwq0h6oedu","sqlExpression":"regional_office,
  product_name"},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]},{"filters":[],"extras":{"time_grain_sqla":"P1M","having":"","where":"(ts_close_date
  is null)"},"applied_time_extras":{},"columns":[],"metrics":["suggested_retail_price"],"annotation_layers":[],"row_limit":0,"row_offset":0,"series_limit":0,"series_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"regional_office,
  product_name","optionName":"metric_7kn5lq10gwe_kwq0h6oedu","sqlExpression":"regional_office,
  product_name"},"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"1__table","viz_type":"table","slice_id":14,"query_mode":"aggregate","groupby":["regional_office","ts_engage_date","product_name","deal_age"],"time_grain_sqla":"P1M","temporal_columns_lookup":{"ts_engage_date":true,"ts_close_date":true,"date_actual":true,"first_day_of_week":true,"last_day_of_week":true,"last_day_of_quarter":true,"first_day_of_year":true,"first_day_of_month":true,"last_day_of_month":true,"first_day_of_quarter":true,"last_day_of_year":true},"metrics":["suggested_retail_price"],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_vlglp171laq_a02ymkf2hu8","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":"ts_close_date
  is null","subject":"ts_close_date"}],"timeseries_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"regional_office,
  product_name","optionName":"metric_7kn5lq10gwe_kwq0h6oedu","sqlExpression":"regional_office,
  product_name"},"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":false,"show_totals":true,"table_timestamp_format":"smart_date","show_cell_bars":false,"color_pn":true,"conditional_formatting":[{"colorScheme":"#ACE1C4","column":"suggested_retail_price","operator":"None"}],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 22965e21-246b-49df-a578-e2a55eb7d78a
version: 1.0.0
dataset_uuid: c7b2363d-9208-475a-9c2a-d007e681c306
