slice_name: QoQ Growth
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 2__table
  viz_type: mixed_timeseries
  x_axis: quarter
  time_grain_sqla: P3M
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_revenue
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 47
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(total_revenue)
    optionName: metric_cku55pzyeed_up1igw7f5ks
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: quarter
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: quarter_over_quarter_growth
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 49
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(quarter_over_quarter_growth)
    optionName: metric_x1odvenrxi_dfofhzg6hb
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    subject: quarter
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: bar
  stack: false
  area: false
  show_value: true
  opacity: 0.2
  markerEnabled: true
  markerSize: 6
  seriesTypeB: line
  stackB: false
  opacityB: 0.2
  markerSizeB: 6
  yAxisIndexB: 1
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  minorSplitLine: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
  - null
  - null
  y_axis_format_secondary: SMART_NUMBER
  logAxisSecondary: false
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[{"col":"quarter","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P3M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P3M","columnType":"BASE_AXIS","sqlExpression":"quarter","label":"quarter","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":47,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_revenue)","optionName":"metric_cku55pzyeed_up1igw7f5ks"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["quarter"],"columns":[],"aggregates":{"SUM(total_revenue)":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":47,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_revenue)","optionName":"metric_cku55pzyeed_up1igw7f5ks"},false]]},{"filters":[{"col":"quarter","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P3M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P3M","columnType":"BASE_AXIS","sqlExpression":"quarter","label":"quarter","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"quarter_over_quarter_growth","description":null,"expression":null,"filterable":true,"groupby":true,"id":49,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(quarter_over_quarter_growth)","optionName":"metric_x1odvenrxi_dfofhzg6hb"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["quarter"],"columns":[],"aggregates":{"AVG(quarter_over_quarter_growth)":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"quarter_over_quarter_growth","description":null,"expression":null,"filterable":true,"groupby":true,"id":49,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(quarter_over_quarter_growth)","optionName":"metric_x1odvenrxi_dfofhzg6hb"},false]]}],"form_data":{"datasource":"2__table","viz_type":"mixed_timeseries","x_axis":"quarter","time_grain_sqla":"P3M","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":47,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE
  PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_revenue)","optionName":"metric_cku55pzyeed_up1igw7f5ks"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"quarter","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"comparison_type":"values","annotation_layers":[],"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"supersetColors","seriesType":"bar","stack":false,"area":false,"show_value":true,"opacity":0.2,"markerEnabled":true,"markerSize":6,"seriesTypeB":"line","stackB":false,"opacityB":0.2,"markerSizeB":6,"yAxisIndexB":1,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","minorSplitLine":false,"truncateXAxis":true,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_bounds_secondary":[null,null],"y_axis_format_secondary":"SMART_NUMBER","logAxisSecondary":false,"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8c7f637e-33ca-4aad-8c46-a81926a2b24d
version: 1.0.0
dataset_uuid: 45e5bfb3-f0d9-4376-8356-3faf2a024cc5
