slice_name: Revenue By Month
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 1__table
  viz_type: table
  slice_id: 2
  query_mode: aggregate
  groupby:
  - mmyyyy
  - year_actual
  - month_name
  time_grain_sqla: P1M
  temporal_columns_lookup:
    ts_engage_date: true
    ts_close_date: true
    date_actual: true
    first_day_of_week: true
    last_day_of_week: true
    first_day_of_month: true
    last_day_of_month: true
    first_day_of_quarter: true
    last_day_of_quarter: true
    first_day_of_year: true
    last_day_of_year: true
  metrics:
  - total_revenue
  all_columns: []
  percent_metrics:
  - total_revenue
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_81lxev703h2_sqw2ar0kgd
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: ts_engage_date
  - clause: WHERE
    comparator: 0
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ju0cwsabnd_8uj6c5q729p
    isExtra: false
    isNew: false
    operator: '>'
    operatorId: GREATER_THAN
    sqlExpression: null
    subject: revenue
  timeseries_limit_metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: mmyyyy
    optionName: metric_fry62n6t35c_tlny0t95d9
    sqlExpression: mmyyyy
  order_by_cols: []
  server_pagination: false
  row_limit: 1000
  server_page_length: 10
  order_desc: false
  show_totals: true
  table_timestamp_format: smart_date
  page_length: null
  show_cell_bars: true
  color_pn: true
  conditional_formatting:
  - colorScheme: '#ACE1C4'
    column: '%total_revenue'
    operator: None
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"ts_engage_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"revenue","op":">","val":0}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":["mmyyyy","year_actual","month_name"],"metrics":["total_revenue"],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"mmyyyy","optionName":"metric_fry62n6t35c_tlny0t95d9","sqlExpression":"mmyyyy"},true]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"mmyyyy","optionName":"metric_fry62n6t35c_tlny0t95d9","sqlExpression":"mmyyyy"},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"contribution","options":{"columns":["total_revenue"],"rename_columns":["%total_revenue"]}}]},{"filters":[{"col":"ts_engage_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"revenue","op":">","val":0}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["total_revenue"],"annotation_layers":[],"row_limit":0,"row_offset":0,"series_limit":0,"series_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"mmyyyy","optionName":"metric_fry62n6t35c_tlny0t95d9","sqlExpression":"mmyyyy"},"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"1__table","viz_type":"table","slice_id":2,"query_mode":"aggregate","groupby":["mmyyyy","year_actual","month_name"],"time_grain_sqla":"P1M","temporal_columns_lookup":{"ts_engage_date":true,"ts_close_date":true,"date_actual":true,"first_day_of_week":true,"last_day_of_week":true,"first_day_of_month":true,"last_day_of_month":true,"first_day_of_quarter":true,"last_day_of_quarter":true,"first_day_of_year":true,"last_day_of_year":true},"metrics":["total_revenue"],"all_columns":[],"percent_metrics":["total_revenue"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_81lxev703h2_sqw2ar0kgd","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"ts_engage_date"},{"clause":"WHERE","comparator":0,"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_ju0cwsabnd_8uj6c5q729p","isExtra":false,"isNew":false,"operator":">","operatorId":"GREATER_THAN","sqlExpression":null,"subject":"revenue"}],"timeseries_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"mmyyyy","optionName":"metric_fry62n6t35c_tlny0t95d9","sqlExpression":"mmyyyy"},"order_by_cols":[],"server_pagination":false,"row_limit":1000,"server_page_length":10,"order_desc":false,"show_totals":true,"table_timestamp_format":"smart_date","page_length":null,"show_cell_bars":true,"color_pn":true,"conditional_formatting":[{"colorScheme":"#ACE1C4","column":"%total_revenue","operator":"None"}],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fcd4c182-ee3e-4b53-9da4-00442e41dc25
version: 1.0.0
dataset_uuid: c7b2363d-9208-475a-9c2a-d007e681c306
