table_name: product_win_rates
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: dev_crm_sales_dbt
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 966b3dec-7a72-4db4-880d-d900afc9b083
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: product_win_rate
  verbose_name: null
  is_dttm: false
  is_active: true
  type: NUMERIC
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: all_deals
  verbose_name: null
  is_dttm: false
  is_active: true
  type: NUMERIC
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: won_deals
  verbose_name: null
  is_dttm: false
  is_active: true
  type: NUMERIC
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: product_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: a0796904-bda0-42bb-bfdc-dd849fc44792
