dbt_company:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: dw
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: sales_dw
      schema: dev
  target: dev
